### ISSUE TITLE
Crash when removing service check

### ISSUE THREAD

**Issue by axel-lebourhis** [Notifiarr/notifiarr#252]
I'm running the client in a docker container and I'm using the "main" tag.
I updated my image today, and I saw NZBGet is now in the download apps, so I wanted to remove it from the services check.
We doing this, the web interface says "Notifiarr client seems to be down ! Hard refresh recommended"
And in the logs I've got that:
```
[ERROR] 2022/07/16 10:02:07 http: panic serving <ip>:58910: runtime error: invalid memory address or nil pointer dereference
goroutine 974 [running]:
net/http.(*conn).serve.func1()
        net/http/server.go:1825 +0xec
panic({0x856be8, 0x1080208})
        runtime/panic.go:844 +0x2ac
github.com/Notifiarr/notifiarr/pkg/client.(*Client).mergeAndValidateNewConfig(0x1692d20, 0x19aa500, 0x1462f00)
        github.com/Notifiarr/notifiarr/pkg/client/handlers_gui.go:631 +0x64c
github.com/Notifiarr/notifiarr/pkg/client.(*Client).handleConfigPost(0x1692d20, {0xa07f48, 0x1e185e0}, 0x1462f00)
        github.com/Notifiarr/notifiarr/pkg/client/handlers_gui.go:534 +0x180
net/http.HandlerFunc.ServeHTTP(0x1714548, {0xa07f48, 0x1e185e0}, 0x1462f00)
        net/http/server.go:2084 +0x34
github.com/Notifiarr/notifiarr/pkg/client.(*Client).checkAuthorized.func1({0xa07f48, 0x1e185e0}, 0x1462e80)
        github.com/Notifiarr/notifiarr/pkg/client/handlers_gui.go:54 +0x33c
net/http.HandlerFunc.ServeHTTP(0x1e185a0, {0xa07f48, 0x1e185e0}, 0x1462e80)
        net/http/server.go:2084 +0x34
github.com/Notifiarr/notifiarr/pkg/client.(*Client).addUsernameHeader.func1({0xa07f48, 0x1e185e0}, 0x1462e80)
        github.com/Notifiarr/notifiarr/pkg/client/handlers.go:176 +0x140
net/http.HandlerFunc.ServeHTTP(0x1e185b0, {0xa07f48, 0x1e185e0}, 0x1462e80)
        net/http/server.go:2084 +0x34
github.com/Notifiarr/notifiarr/pkg/client.(*Client).countRequest.func1({0xa07fd4, 0x1c400f0}, 0x1462e80)
        github.com/Notifiarr/notifiarr/pkg/client/handlers.go:194 +0x28c
net/http.HandlerFunc.ServeHTTP(0x1e185c0, {0xa07fd4, 0x1c400f0}, 0x1462e80)
        net/http/server.go:2084 +0x34
github.com/Notifiarr/notifiarr/pkg/client.(*Client).fixForwardedFor.func1({0xa07fd4, 0x1c400f0}, 0x1462e80)
        github.com/Notifiarr/notifiarr/pkg/client/handlers.go:210 +0x370
net/http.HandlerFunc.ServeHTTP(0x1e185d0, {0xa07fd4, 0x1c400f0}, 0x1462e80)
        net/http/server.go:2084 +0x34
github.com/gorilla/mux.(*Router).ServeHTTP(0x1bcd920, {0xa07fd4, 0x1c400f0}, 0x1462c80)
        github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1dc
github.com/lestrrat-go/apache-logformat.(*ApacheLog).Wrap.func1({0xa08610, 0x19aa460}, 0x1462c80)
        github.com/lestrrat-go/apache-logformat@v0.0.0-20200929122403-cd9b7dc018c7/logformat.go:65 +0x180
net/http.HandlerFunc.ServeHTTP(0x1758ed0, {0xa08610, 0x19aa460}, 0x1462c80)
        net/http/server.go:2084 +0x34
github.com/Notifiarr/notifiarr/pkg/client.(*Client).stripSecrets.func1({0xa08610, 0x19aa460}, 0x1462c80)
        github.com/Notifiarr/notifiarr/pkg/client/handlers.go:167 +0x1b0
net/http.HandlerFunc.ServeHTTP(0x1758ee8, {0xa08610, 0x19aa460}, 0x1462c80)
        net/http/server.go:2084 +0x34
net/http.(*ServeMux).ServeHTTP(0x196a9f0, {0xa08610, 0x19aa460}, 0x1462c80)
        net/http/server.go:2462 +0x164
net/http.serverHandler.ServeHTTP({0x1862360}, {0xa08610, 0x19aa460}, 0x1462c80)
        net/http/server.go:2916 +0x408
net/http.(*conn).serve(0x14dad20, {0xa08914, 0x17522a0})
        net/http/server.go:1966 +0x654
created by net/http.(*Server).Serve
        net/http/server.go:3071 +0x4e0
```

**Comment by davidnewhall** [comment]
You mean `unstable` tag? Not sure there is a `main` tag.

**Comment by davidnewhall** [comment]
Okay there is a main tag. Something is pushing that. I'd suggest `unstable` for now until the next release.

**Comment by axel-lebourhis** [comment]
Ok sure I'll switch to unstable then, but removing the service by hand fixed the issue on latest main tag.

**Comment by davidnewhall** [comment]
Can you show me the startup log for the current main tag you're using? The lines that begin with `=>` in the main app log when it starts up.

**Comment by davidnewhall** [comment]
Thanks for the report, I was able to reproduce the issue. Will get it fixed!

**Comment by axel-lebourhis** [comment]
Awesome mate ! Glad to help.
