### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by thatnovaguy** [Notifiarr/notifiarr#287]
Not sure what I've done wrong but I've been met with this error when trying to do an initial setup of notifiarr on unraid.
```
[ERROR] 2022/08/20 13:17:20 Go Panic! This is a bug please report it on github: https://github.com/Notifiarr/notifiarr/issues/new
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
main.main.func1()
        github.com/Notifiarr/notifiarr/main.go:21 +0x3d
panic({0xc64ba0, 0x1555340})
        runtime/panic.go:884 +0x212
github.com/Notifiarr/notifiarr/pkg/services.(*Config).collectDownloadApps(0xc0002c46e0, {0x159ce50?, 0xf?, 0xd1e7b0?})
        github.com/Notifiarr/notifiarr/pkg/services/apps.go:198 +0x36b
github.com/Notifiarr/notifiarr/pkg/services.(*Config).collectApps(0xc0002c46e0)
        github.com/Notifiarr/notifiarr/pkg/services/apps.go:18 +0x9f
github.com/Notifiarr/notifiarr/pkg/services.(*Config).Setup(0xc0002c46e0, {0x0?, 0x0, 0x0})
        github.com/Notifiarr/notifiarr/pkg/services/services.go:29 +0x85
github.com/Notifiarr/notifiarr/pkg/configfile.(*Config).Get(0xc0002e6140, 0xc0002ec090)
        github.com/Notifiarr/notifiarr/pkg/configfile/config.go:150 +0x39e
github.com/Notifiarr/notifiarr/pkg/client.(*Client).loadConfiguration(0xc0002c4780)
        github.com/Notifiarr/notifiarr/pkg/client/start.go:173 +0x1a5
github.com/Notifiarr/notifiarr/pkg/client.(*Client).start(0xc0002c4780)
        github.com/Notifiarr/notifiarr/pkg/client/start.go:106 +0x36
github.com/Notifiarr/notifiarr/pkg/client.Start()
        github.com/Notifiarr/notifiarr/pkg/client/start.go:101 +0xda
main.main()
        github.com/Notifiarr/notifiarr/main.go:25 +0x6a
[ERROR] 2022/08/20 13:20:43 Go Panic! This is a bug please report it on github: https://github.com/Notifiarr/notifiarr/issues/new
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
main.main.func1()
        github.com/Notifiarr/notifiarr/main.go:21 +0x3d
panic({0xc64ba0, 0x1555340})
        runtime/panic.go:884 +0x212
github.com/Notifiarr/notifiarr/pkg/services.(*Config).collectDownloadApps(0xc0001e4000, {0x159ce50?, 0xc0000de5c0?, 0x3c?})
        github.com/Notifiarr/notifiarr/pkg/services/apps.go:198 +0x36b
github.com/Notifiarr/notifiarr/pkg/services.(*Config).collectApps(0xc0001e4000)
        github.com/Notifiarr/notifiarr/pkg/services/apps.go:18 +0x9f
github.com/Notifiarr/notifiarr/pkg/services.(*Config).Setup(0xc0001e4000, {0x0?, 0x0, 0x0})
        github.com/Notifiarr/notifiarr/pkg/services/services.go:29 +0x85
github.com/Notifiarr/notifiarr/pkg/configfile.(*Config).Get(0xc0000f5180, 0xc0001bc120)
        github.com/Notifiarr/notifiarr/pkg/configfile/config.go:150 +0x39e
github.com/Notifiarr/notifiarr/pkg/client.(*Client).loadConfiguration(0xc0001e40a0)
        github.com/Notifiarr/notifiarr/pkg/client/start.go:173 +0x1a5
github.com/Notifiarr/notifiarr/pkg/client.(*Client).start(0xc0001e40a0)
        github.com/Notifiarr/notifiarr/pkg/client/start.go:106 +0x36
github.com/Notifiarr/notifiarr/pkg/client.Start()
        github.com/Notifiarr/notifiarr/pkg/client/start.go:101 +0xda
main.main()
        github.com/Notifiarr/notifiarr/main.go:25 +0x6a
```

Sorry if it's something obvious that I'm overlooking.

**Comment by davidnewhall** [comment]
This is not your doing. This is a bug in how NZBGet service checks are setup. 

Do you have NZBGet configured in your config file?

**Comment by thatnovaguy** [comment]
> This is not your doing. This is a bug in how NZBGet service checks are setup.
> 
> Do you have NZBGet configured in your config file?

I do. I've double checked the nzbget entry but I don't see anything out of the norm. Is there something I need to do within nzbget?

**Comment by davidnewhall** [comment]
Can you share your `[[nzbget]]` config snippet? I'm pretty sure I have a fix for this, but I'm still not sure what caused it.

**Comment by thatnovaguy** [comment]
Sure.
`[[nzbget]]
#name     = "nzbgetvpn"  # Set a name to enable checks of your service.
#url      = "http://192.168.1.186:6789/"
#user     = "user"
#pass     = "password"`

**Comment by davidnewhall** [comment]
Okay, that makes sense. It's crashing because you configured an empty nzbget. Lines beginning with `#` are ignored comments. Remove the `#` from the `url` line at minimum. Probably the other 3 as well. Then it'll start working without crashing.

**Comment by thatnovaguy** [comment]
OH! I'm sorry that should've been obvious. Thank you!
