### ISSUE TITLE
runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by TRaSH-** [Notifiarr/notifiarr#316]
This morning i noticed that notifiarrr wasn't running.
The container logs showed the following
```
[ERROR] 2022/09/18 03:49:48 Go Panic! This is a bug please report it on github: https://github.com/Notifiarr/notifiarr/issues/new
runtime error: index out of range [0] with length 0
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
main.main.func1()
        github.com/Notifiarr/notifiarr/main.go:21 +0x3d
panic({0xcdf440, 0xc0003f4180})
        runtime/panic.go:884 +0x212
github.com/Notifiarr/notifiarr/pkg/apps.(*Apps).setupSabNZBd(0xc0003562c0)
        github.com/Notifiarr/notifiarr/pkg/apps/integrations.go:80 +0x1c5
github.com/Notifiarr/notifiarr/pkg/apps.(*Apps).Setup(0xc0003562c0)
        github.com/Notifiarr/notifiarr/pkg/apps/setup.go:103 +0xf9
github.com/Notifiarr/notifiarr/pkg/configfile.(*Config).Get(0xc00034c360, 0xc000372090)
        github.com/Notifiarr/notifiarr/pkg/configfile/config.go:152 +0x413
github.com/Notifiarr/notifiarr/pkg/client.(*Client).loadConfiguration(0xc000346820, {0xe94d10?, 0xc000026068?})
        github.com/Notifiarr/notifiarr/pkg/client/start.go:196 +0x1b8
github.com/Notifiarr/notifiarr/pkg/client.(*Client).start(0xc000346820, {0xe94d10, 0xc000026068})
        github.com/Notifiarr/notifiarr/pkg/client/start.go:114 +0x4f
github.com/Notifiarr/notifiarr/pkg/client.Start()
        github.com/Notifiarr/notifiarr/pkg/client/start.go:109 +0x118
main.main()
        github.com/Notifiarr/notifiarr/main.go:25 +0x6a

** Press ANY KEY to close this window ** 
```

**Comment by davidnewhall** [comment]
Thank you, I'll fix this shortly.
