### ISSUE TITLE
Unable to Save & Reload when adding a SabNZB

### ISSUE THREAD

**Issue by nathang21** [Notifiarr/notifiarr#743]
I am unable to add SabNZB as a download app, however qBittorrent is working fine. Upon clicking test, I get a successful response, but when trying to "Save & Reload" in the Notifiarr client, the WeB UI shows an error:
```
Web Server Error
Notifiarr client appears to be down! Hard refresh recommended.
```

I've tried a hard refresh, tried restarting the instance via the web UI, as well as the entire docker container. I am using the latest version, herei s some various metadar about my setup do let me know if you need additional information. 
![Screenshot 2024-05-29 at 2 13 59 PM](https://github.com/Notifiarr/notifiarr/assets/7875110/95482069-5e58-4152-832d-a1e4d02998e6)

Error from Logs:
```
2024-05-29
14:09:47
172.23.0.1 - <USERNAME> [29/May/2024:14:09:47 -0400] "POST /ui/reconfig HTTP/1.1" 200 - "<IP_ADDRESS>/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" - 2ms
2024-05-29
14:09:47
[ERROR] 2024/05/29 14:09:47 http: panic serving 172.23.0.1:36964: reflect: indirection through nil pointer to embedded struct
2024-05-29
14:09:47
goroutine 32629 [running]:
2024-05-29
14:09:47
net/http.(*conn).serve.func1()
2024-05-29
14:09:47
net/http/server.go:1898 +0xbe
2024-05-29
14:09:47
panic({0xec9820?, 0x1281920?})
2024-05-29
14:09:47
runtime/panic.go:770 +0x132
2024-05-29
14:09:47
reflect.Value.FieldByIndex({0xfe65a0?, 0xc000834578?, 0x0?}, {0xc000b23540, 0x2, 0xfc05c0?})
2024-05-29
14:09:47
reflect/value.go:1324 +0x174
2024-05-29
14:09:47
reflect.Value.FieldByName({0xfe65a0?, 0xc000834578?, 0xfe65a0?}, {0xe4e52a?, 0xc000834558?})
2024-05-29
14:09:47
reflect/value.go:1363 +0x14c
2024-05-29
14:09:47
github.com/gorilla/schema.(*Decoder).setDefaults(0x1dec860, {0x1297bc8, 0xfe65a0}, {0xfe65a0?, 0xc000834578?, 0xc000e1fc08?})
2024-05-29
14:09:47
github.com/gorilla/schema@v1.3.0/decoder.go:108 +0x1f4
2024-05-29
14:09:47
github.com/gorilla/schema.(*Decoder).setDefaults(0x1dec860, {0x1297bc8, 0xfde5a0}, {0xfde5a0?, 0xc000834540?, 0x2e?})
2024-05-29
14:09:47
github.com/gorilla/schema@v1.3.0/decoder.go:111 +0x2c5
2024-05-29
14:09:47
github.com/gorilla/schema.(*Decoder).setDefaults(0x1dec860, {0x1297bc8, 0x100f2c0}, {0x100f2c0?, 0xc000ad3080?, 0xc000b23180?})
2024-05-29
14:09:47
github.com/gorilla/schema@v1.3.0/decoder.go:113 +0x3d2
2024-05-29
14:09:47
github.com/gorilla/schema.(*Decoder).setDefaults(0x1dec860, {0x1297bc8, 0x101da60}, {0x101da60?, 0xc000a5e280?, 0xc000a5e280?})
2024-05-29
14:09:47
github.com/gorilla/schema@v1.3.0/decoder.go:113 +0x3d2
2024-05-29
14:09:47
github.com/gorilla/schema.(*Decoder).Decode(0x1dec860, {0x100c380?, 0xc000a5e280?}, 0xc000dc6900)
2024-05-29
14:09:47
github.com/gorilla/schema@v1.3.0/decoder.go:87 +0x3fb
2024-05-29
14:09:47
github.com/Notifiarr/notifiarr/pkg/client.(*Client).mergeAndValidateNewConfig(0xc00014c0b0, 0xc000a5e280, 0xc000706b40)
2024-05-29
14:09:47
github.com/Notifiarr/notifiarr/pkg/client/handlers_gui.go:722 +0x4be
2024-05-29
14:09:47
github.com/Notifiarr/notifiarr/pkg/client.(*Client).handleConfigPost(0xc00014c0b0, {0x128a130, 0xc000bca0d8}, 0xc000706b40)
2024-05-29
14:09:47
github.com/Notifiarr/notifiarr/pkg/client/handlers_gui.go:617 +0x185
2024-05-29
14:09:47
net/http.HandlerFunc.ServeHTTP(0xc0007067e0?, {0x128a130?, 0xc000bca0d8?}, 0x1927330?)
2024-05-29
14:09:47
net/http/server.go:2166 +0x29
2024-05-29
14:09:47
github.com/Notifiarr/notifiarr/pkg/client.(*Client).checkAuthorized-fm.(*Client).checkAuthorized.func1({0x128a130, 0xc000bca0d8}, 0xc0007067e0)
2024-05-29
14:09:47
github.com/Notifiarr/notifiarr/pkg/client/handlers_gui.go:63 +0x162
2024-05-29
14:09:47
net/http.HandlerFunc.ServeHTTP(0xc000433b30?, {0x128a130?, 0xc000bca0d8?}, 0xc000b32330?)
2024-05-29
14:09:47
net/http/server.go:2166 +0x29
2024-05-29
14:09:47
github.com/Notifiarr/notifiarr/pkg/client.(*Client).addUsernameHeader-fm.(*Client).addUsernameHeader.func1({0x128a130, 0xc000bca0d8}, 0xc0007067e0)
2024-05-29
14:09:47
github.com/Notifiarr/notifiarr/pkg/client/handlers.go:194 +0x8c
2024-05-29
14:09:47
net/http.HandlerFunc.ServeHTTP(0xc00015a0f0?, {0x128a130?, 0xc000bca0d8?}, 0x1?)
2024-05-29
14:09:47
net/http/server.go:2166 +0x29
2024-05-29
14:09:47
github.com/Notifiarr/notifiarr/pkg/client.(*Client).countRequest-fm.(*Client).countRequest.func1({0x128a190, 0xc000980240}, 0xc0007067e0)
2024-05-29
14:09:47
github.com/Notifiarr/notifiarr/pkg/client/handlers.go:212 +0x246
2024-05-29
14:09:47
net/http.HandlerFunc.ServeHTTP(0xc000433b30?, {0x128a190?, 0xc000980240?}, 0xc000b32150?)
2024-05-29
14:09:47
net/http/server.go:2166 +0x29
2024-05-29
14:09:47
github.com/Notifiarr/notifiarr/pkg/client.(*Client).fixForwardedFor-fm.(*Client).fixForwardedFor.func1({0x128a190, 0xc000980240}, 0xc0007067e0)
2024-05-29
14:09:47
github.com/Notifiarr/notifiarr/pkg/client/handlers.go:233 +0x2cd
2024-05-29
14:09:47
net/http.HandlerFunc.ServeHTTP(0xc0007066c0?, {0x128a190?, 0xc000980240?}, 0x6fa4f5?)
2024-05-29
14:09:47
net/http/server.go:2166 +0x29
2024-05-29
14:09:47
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0008ea000, {0x128a190, 0xc000980240}, 0xc0007065a0)
2024-05-29
14:09:47
github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1e2
2024-05-29
14:09:47
github.com/Notifiarr/notifiarr/pkg/client.(*Client).StartWebServer.(*ApacheLog).Wrap.func1({0x128a3d0, 0xc000152000}, 0xc0007065a0)
2024-05-29
14:09:47
github.com/lestrrat-go/apache-logformat/v2@v2.0.6/logformat.go:65 +0x18b
2024-05-29
14:09:47
net/http.HandlerFunc.ServeHTTP(0xc000433b30?, {0x128a3d0?, 0xc000152000?}, 0xc000b101c5?)
2024-05-29
14:09:47
net/http/server.go:2166 +0x29
2024-05-29
14:09:47
github.com/Notifiarr/notifiarr/pkg/client.(*Client).StartWebServer.(*Client).stripSecrets.func2({0x128a3d0, 0xc000152000}, 0xc0007065a0)
2024-05-29
14:09:47
github.com/Notifiarr/notifiarr/pkg/client/handlers.go:184 +0xef
2024-05-29
14:09:47
net/http.HandlerFunc.ServeHTTP(0xc0001152b0?, {0x128a3d0?, 0xc000152000?}, 0x10?)
2024-05-29
14:09:47
net/http/server.go:2166 +0x29
2024-05-29
14:09:47
net/http.(*ServeMux).ServeHTTP(0x411f65?, {0x128a3d0, 0xc000152000}, 0xc0007065a0)
2024-05-29
14:09:47
net/http/server.go:2683 +0x1ad
2024-05-29
14:09:47
net/http.serverHandler.ServeHTTP({0x12878c0?}, {0x128a3d0?, 0xc000152000?}, 0x6?)
2024-05-29
14:09:47
net/http/server.go:3137 +0x8e
2024-05-29
14:09:47
net/http.(*conn).serve(0xc000d00360, {0x128c348, 0xc00067a480})
2024-05-29
14:09:47
net/http/server.go:2039 +0x5e8
2024-05-29
14:09:47
created by net/http.(*Server).Serve in goroutine 105
2024-05-29
14:09:47
net/http/server.go:3285 +0x4b4
```

**Comment by nathang21** [comment]
Found on discord, looks like `:latest` is broken, temporarily using `:unstable` resolved it.

**Comment by bakerboy448** [comment]
:latest is fixed / fine ( or should be) https://github.com/Notifiarr/notifiarr/releases/tag/v0.7.2

Use ghcr not dockerhub, there was some issues pushing that build to dockerhub
